import React from "react";
import type {Metadata} from "next";
import "./globalStyles/normalize.css";
import "./globalStyles/globals.css";
import "./globalStyles/header.css";
import 'bootstrap/dist/css/bootstrap.css';
import Layout from "@/components/layouts/Layout";


export const metadata: Metadata = {
  title: "Магазин сладостей",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
    <body><Layout>{children}</Layout></body>
    </html>
  );
}
